import Script from "next/script"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* <Script async src="https://www.googletagmanager.com/gtag/js?id=G-K5STSPVGTM"></Script>
        <Script id="google-analytics">
          {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-K5STSPVGTM');`}
        </Script> */}

        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-L17M5S7FWN"></Script>
        <Script id="google-analytics">
          {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-L17M5S7FWN');`}
        </Script>
      </head>
      <body>{children}</body>
    </html>
  )
}
